# This is a basic workflow to help you get started with Actions

name: Publish iOS app to App Store

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   release-ios:
    name: Build and release iOS app
    runs-on: macos-latest
    env:
      GIT_URL: ${{ secrets.MATCH_CERT_GIT_URL }}
      MATCH_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
      FASTLANE_PASSWORD: ${{ secrets.APPLE_ACCOUNT_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.x"
      - name: Install Fastlane
        run: cd DDYZD_V2 && bundle install && cd ..
      - name: Install packages
        run: yarn install
      - name: Install pods
        run: cd DDYZD_V2 && pod install && cd ..
      - name: Set Appstore Connect User
        run: cd DDYZD_V2 && bundle exec fastlane fastlane-credentials add --username "kimxwan0319@naver.com" --password ${{ secrets.APPLE_ACCOUNT_PASSWORD }} && cd ..
      - name: Deploy App
        run: cd DDYZD_V2 && bundle exec fastlane github && cd ..
